name: CI

on:
  push:
    paths:
      - "frontend/**"
  pull_request:
    paths:
      - "frontend/**"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        working-directory: ./frontend
        run: yarn install

      - name: Code Check
        working-directory: ./frontend
        run: |
          yarn run lint
          yarn run format
          git diff --exit-code

      - name: Build
        working-directory: ./frontend
        run: yarn run build
